const $=s=>document.querySelector(s),drop=$("#drop"),file=$("#file"),chosen=$("#chosen"),btn=$("#deployBtn"),log=$("#log"),name=$("#name");
let selected=null;
let p=0;const pb=$("#progress"),dots=$("#dots");const introTimer=setInterval(()=>{p+=3+Math.random()*5;pb.style.width=Math.min(p,100)+"%";if(p>=100){clearInterval(introTimer);setTimeout(()=>{$("#intro").style.opacity="0";$("#intro").style.transition=".5s";setTimeout(()=>{$("#intro").remove();$("#app").hidden=false},520)},250)}},90);
setInterval(()=>dots.textContent=".".repeat((Date.now()/350|0)%4||3),150);
function logmsg(x,ok=false){let t=new Date().toLocaleTimeString("id-ID",{hour12:false});log.innerHTML+=`\n<span class="muted">[${t}]</span> <span class="${ok?"ok":""}">●</span> ${esc(x)}`;log.scrollTop=log.scrollHeight}
function esc(x){return String(x).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
drop.onclick=()=>file.click();file.onchange=()=>pick(file.files[0]);drop.ondragover=e=>{e.preventDefault()};drop.ondrop=e=>{e.preventDefault();pick(e.dataTransfer.files[0])};
function pick(f){if(!f)return;if(!/\.(html?|zip)$/i.test(f.name))return toast("HANYA HTML ATAU ZIP");selected=f;chosen.textContent="✓ "+f.name;btn.disabled=false;logmsg("Berkas dipilih: "+f.name,true)}
function readBase64(f){return new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>res(r.result.split(",")[1]);r.onerror=rej;r.readAsDataURL(f)})}
btn.onclick=async()=>{if(!selected)return;let n=(name.value.trim()||"felix-project").toLowerCase().replace(/[^a-z0-9-]/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"").slice(0,50);btn.disabled=true;logmsg("Mengirim berkas ke server...");try{let data=await readBase64(selected);let r=await fetch("/api/deploy",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:n,filename:selected.name,data})});let j=await r.json();if(!r.ok)throw Error(j.error||"Deployment gagal");logmsg("Deployment berhasil: "+j.url,true);save({name:n,url:j.url,date:new Date().toLocaleDateString("id-ID")});render();toast("BERHASIL → "+j.url);window.open(j.url,"_blank")}catch(e){logmsg(e.message);toast("DEPLOYMENT GAGAL")}finally{btn.disabled=false}};
function get(){return JSON.parse(localStorage.getItem("felix_projects")||"[]")}function save(x){let a=get().filter(y=>y.name!==x.name);a.unshift(x);localStorage.setItem("felix_projects",JSON.stringify(a.slice(0,20)))}function render(){let a=get(),el=$("#list");if(!a.length){el.innerHTML='<div class="empty">BELUM ADA PROJECT</div>';return}el.innerHTML=a.map((x,i)=>`<div class="project"><div><div class="pname">${esc(x.name)}</div><div class="date">${esc(x.date)}</div></div><div class="actions"><button onclick="openUrl(${i})">◦ DOMAIN</button> <button class="del" onclick="del(${i})">DELETE</button></div></div>`).join("")}window.openUrl=i=>{let a=get();if(a[i]?.url)location.href=a[i].url};window.del=i=>{let a=get();a.splice(i,1);localStorage.setItem("felix_projects",JSON.stringify(a));render()};function toast(x){let t=$("#toast");t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),3000)}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.go).scrollIntoView({behavior:"smooth"}));$("#refresh").onclick=render;render();
