'use client';
import {useEffect,useState} from 'react';
const defaults={title:'IX-B',subtitle:'Bersinar',school:'SMP NEGERI 1 PURI',developer:'Khalfani Felix Fajar Ardiyanto',tiktok:'',instagram:'',whatsapp:''};
const students0=Array.from({length:32},(_,i)=>({no:i+1,name:`Siswa ${String(i+1).padStart(2,'0')}`,gender:i<18?'Laki-laki':'Perempuan',photo:''}));
const officers0=[['Wali Kelas','Arum Wahyuningtiyas, S.Pd.'],['Ketua Kelas','Punky Ardi Saputra'],['Wakil Ketua Kelas','Rayvan Raja Abdillah'],['Bendahara 1','Citra Dwi Setyowati'],['Bendahara 2','Fatimatul Uswatun Hasanah'],['Sekretaris 1','Wisesti Rafa Kayanya'],['Sekretaris 2','Sofiatul Jayanti']];
function load(k,d){try{return JSON.parse(localStorage.getItem(k)||'null')||d}catch{return d}};
export default function Admin(){const [auth,setAuth]=useState(false),[login,setLogin]=useState({username:'',password:''}),[err,setErr]=useState(''),[info,setInfo]=useState(defaults),[students,setStudents]=useState(students0),[officers,setOfficers]=useState(officers0),[msg,setMsg]=useState('');
 useEffect(()=>{fetch('/api/auth/me').then(r=>r.json()).then(d=>{setAuth(!!d.authenticated);if(d.authenticated){setInfo(load('ixb_info',defaults));setStudents(load('ixb_students',students0));setOfficers(load('ixb_officers',officers0))}})},[]);
 const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 async function signin(e){e.preventDefault();const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(login)});const d=await r.json();if(!r.ok)return setErr(d.error||'Login gagal');setAuth(true);setInfo(load('ixb_info',defaults));setStudents(load('ixb_students',students0));setOfficers(load('ixb_officers',officers0));setErr('')}
 function setI(k,v){const n={...info,[k]:v};setInfo(n);save('ixb_info',n)} function setS(no,k,v){const n=students.map(x=>x.no===no?{...x,[k]:v}:x);setStudents(n);save('ixb_students',n)} function setO(i,v){const n=officers.map((x,j)=>j===i?[x[0],v]:x);setOfficers(n);save('ixb_officers',n)}
 async function uploadStudent(no,e){const f=e.target.files?.[0];if(!f)return;const fd=new FormData();fd.append('file',f);fd.append('kind','student');fd.append('studentNo',no);const r=await fetch('/api/upload',{method:'POST',body:fd});const d=await r.json();if(r.ok){setS(no,'photo',d.url);setMsg('Foto siswa tersimpan.')}else setMsg(d.error||'Upload gagal')}
 if(!auth)return <div className="adminPage"><div className="adminLogin"><div className="terminal">// restricted_area</div><h1>IX-B ADMIN</h1><p>Panel ini tidak ditampilkan pada website publik.</p><form onSubmit={signin}><input placeholder="Username" value={login.username} onChange={e=>setLogin({...login,username:e.target.value})}/><input type="password" placeholder="Password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button>[ LOGIN ]</button>{err&&<small className="error">{err}</small>}</form></div></div>;
 return <div className="adminPage"><div className="adminTop"><h1>IX-B ADMIN</h1><button onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});location.reload()}}>[ LOGOUT ]</button></div><div className="adminGrid"><section><div className="panel"><div className="terminal">// identity</div><h2>Identitas Website</h2>{[['title','Judul'],['subtitle','Subjudul'],['school','Sekolah'],['developer','Developer'],['tiktok','TikTok'],['instagram','Instagram'],['whatsapp','WhatsApp Channel']].map(([k,l])=><label key={k}>{l}<input value={info[k]} onChange={e=>setI(k,e.target.value)}/></label>)}</div><div className="panel"><div className="terminal">// structure</div><h2>Struktur Kelas</h2>{officers.map((o,i)=><label key={i}>{o[0]}<input value={o[1]} onChange={e=>setO(i,e.target.value)}/></label>)}</div></section><section><div className="panel"><div className="terminal">// students</div><h2>32 Murid</h2>{students.map(s=><div className="studentEdit" key={s.no}>{s.photo?<img src={s.photo}/>:<div className="mini">{s.no}</div>}<input value={s.name} onChange={e=>setS(s.no,'name',e.target.value)}/><select value={s.gender} onChange={e=>setS(s.no,'gender',e.target.value)}><option>Laki-laki</option><option>Perempuan</option></select><label className="fileBtn">FOTO<input type="file" accept="image/*" onChange={e=>uploadStudent(s.no,e)}/></label></div>)}</div></section></div>{msg&&<div className="toast">{msg}</div>}</div>}
